version: '3'
services: 
  web:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - '80:4000'
    links:
      - prisma
      - mongo
  prisma:
    container_name: prisma
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: 'Azh45tZEn454vDQ3JK94rdnL0'
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: mongo
            uri: 'mongodb://prisma:prisma@mongo'
  mongo:
    container_name: mongo
    image: mongo:3.6
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: prisma
      MONGO_INITDB_ROOT_PASSWORD: prisma
    volumes:
      - mongo:/var/lib/mongo
volumes:
  mongo: