export const PUB_NEW_AVIS = 'PUB_NEW_AVIS';
export const PUB_NEW_DEMANDE = 'PUB_NEW_DEMANDE';
export const PUB_NEW_OFFERING = 'PUB_NEW_OFFERING';
export const PUB_UPDATE_APPLIED_TO = 'PUB_UPDATE_APPLIED_TO';
export const PUB_SELECTED_EVENT_DAY = 'PUB_SELECTED_EVENT_DAY';
